# Generated by Django 5.2.4 on 2025-07-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_seller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Rastreamento'),
        ),
    ]
