# Generated by Django 6.0.7 on 2026-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Jeci Store', max_length=100, verbose_name='Nome do Site')),
                ('contact_email', models.EmailField(default='contato@jecistore.com.br', max_length=254, verbose_name='E-mail de Contato')),
                ('whatsapp_number', models.CharField(default='5561998504516', help_text='Exemplo: 5561998504516 (código do país + DDD + número)', max_length=20, verbose_name='Número do WhatsApp (Sem espaços/símbolos)')),
                ('whatsapp_display', models.CharField(default='(61) 99850-4516', help_text='Exemplo: (61) 99850-4516', max_length=30, verbose_name='WhatsApp Formatado (Para Exibição)')),
                ('business_hours', models.CharField(default='Segunda a Sexta, das 9h às 18h', max_length=100, verbose_name='Horário de Atendimento')),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
